"""Add user_id to CensusEntry, remove unique constraint

Revision ID: c5f0d721a741
Revises: 545ba14d73ef
Create Date: 2025-07-22 09:40:36.736834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f0d721a741'
down_revision = '545ba14d73ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_census_entry')
    with op.batch_alter_table('census_entry', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key( 'censusentry_user_id_fk', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('census_entry', schema=None) as batch_op:
        batch_op.drop_constraint( 'censusentry_user_id_fk', type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_census_entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entry_date', sa.DATE(), nullable=False),
    sa.Column('m_old_male', sa.INTEGER(), nullable=True),
    sa.Column('m_old_female', sa.INTEGER(), nullable=True),
    sa.Column('m_old_child', sa.INTEGER(), nullable=True),
    sa.Column('m_new_male', sa.INTEGER(), nullable=True),
    sa.Column('m_new_female', sa.INTEGER(), nullable=True),
    sa.Column('m_new_child', sa.INTEGER(), nullable=True),
    sa.Column('e_old_male', sa.INTEGER(), nullable=True),
    sa.Column('e_old_female', sa.INTEGER(), nullable=True),
    sa.Column('e_old_child', sa.INTEGER(), nullable=True),
    sa.Column('e_new_male', sa.INTEGER(), nullable=True),
    sa.Column('e_new_female', sa.INTEGER(), nullable=True),
    sa.Column('e_new_child', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('censusentry_user_id_fk')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_date')
    )
    # ### end Alembic commands ###
