"""Ensure user_id and per-user logic

Revision ID: e9602b6ad07f
Revises: aa2acfc36fa3
Create Date: 2025-07-22 10:08:13.005455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9602b6ad07f'
down_revision = 'aa2acfc36fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('census_entry', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('censusentry_user_id_fk', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('census_entry', schema=None) as batch_op:
        batch_op.drop_constraint('censusentry_user_id_fk', type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
